[package]
name = "zeromq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.10.0"
system = {version = "0.1.0", path = "../system"}
chrono = "0.4.38"

